application: shit4bash
version: 1
runtime: python27
api_version: 1
threadsafe: true

handlers:
- url: /football/update
  login: admin
  script: getFootballScore.application
- url: /.*
  script: getFootballScore.application

libraries:
- name: lxml
  version: "latest"
